language: cpp

install:
  - pip install --user -q conan
  - conan user

script:
  - mkdir build && cd build
  - conan install .. --build
  - cmake ..
  - cmake --build .
  - ./test-ci
  - ./test_hello-ci